name: s3-bucket-perma-link
description: This chart deploys a simple web server that provides permanent links to specific S3 bucket resources. It allows you to define static URL paths that always point to specific files in your S3 buckets.
version: 1.0.5
appVersion: v0.2.2
apiVersion: v2
home: https://github.com/timschoenle/charts
sources:
  - https://github.com/timschoenle/s3-bucket-perma-link
maintainers:
  - name: Tim Sch√∂nle
    email: contact@tim-schoenle.de
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"