name: portfolio
description: Personal portfolio built with Next.js.
version: 1.0.10
appVersion: v1.5.0
apiVersion: v2
home: https://github.com/TimSchoenle/helm-charts
sources:
  - https://github.com/TimSchoenle/Portfolio
maintainers:
  - name: Tim Sch√∂nle
    email: contact@tim-schoenle.de
dependencies:
  - name: common
    version: 0.1.1
    repository: "file://../common"
