{{- if and (not .Values.application.github.secretName) .Values.application.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.application.github.token | quote }}
{{- end }}
