name: netcup-offer-bot
description: This chart deploys the Netcup Offer Bot, which monitors https://www.netcup-sonderangebote.de/ RSS feed and sends notifications to Discord webhooks when new offers are available.
version: 2.0.1
appVersion: v1.3.1
apiVersion: v2
home: https://github.com/TimSchoenle/charts
sources:
  - https://github.com/TimSchoenle/netcup-offer-bot
maintainers:
  - name: Tim Sch√∂nle
    email: contact@tim-schoenle.de
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"